# -*- coding: utf-8 -*-
"""wtorkowe_kody.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F7XFdYQ1ZzCyrrQhjxpybKcyvO8oW0Q_
"""

"a" < "b"
"Adrian" < "Adrianny"
"adrian" < "Adrianny"
"adrian" > "Adrian"
"Polska" != "Polski"

lista = [i for i in range(5)]
print(lista)

lista2 = ["1","2","3","4","5"]
liczby = [int(i) for i in lista2]
print(liczby)

liczba1 = 1
liczba2 = 1

if liczba1 > liczba2:
    print("Pierwsza liczba jest większa")
elif liczba1 < liczba2:
    print("Pierwsza liczba jest mniejsza")
else:
    print("Stan liczb jest nieznany!")

liczba = int(input("Podaj liczbę całkowitą: "))
if liczba < 10:
    print("To jest mała liczba")
elif 9 < liczba < 100:
    print("To już spora liczba")
else:
    print("To musi być wielka liczba!")

liczba = int(input("Podaj liczbę całkowitą: "))
lista = [1,3,5,7,9]
if liczba not in lista:
    print("Podana liczba nie znajduję się w zbiorze")

nic = None
pusty = ""

if not nic:
    print("None to False")
if not pusty:
    print("Pusty ciąg do też False")
if nic == pusty:
    print("None i pusty ciąg to bool w postaci False")

licznik = 0
while True:
    licznik += 1
    print(str(licznik) + " mniejsze od 5")
    if licznik > 10:
        break

lista = []
print("Podaj liczby, które chcesz umieścić w liście: ")
print("Albo wpisz 'stop' aby zakończyć...")
while True:
    wejscie = input()
    if wejscie == 'stop' or wejscie == 's':
        break
    lista.append(int(wejscie))
print("Twoja lista: ",lista)